[package]
name = "scheme-llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = {version = "0.3.0", features=["llvm17-0"]}
llvm-sys = {version = "170", features=["prefer-dynamic"]}